input {
  file {
    path => "/var/log/suricata/eve.json"
    start_position => "beginning"
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "suricata-%{+YYYY.MM.dd}"
  }
}