[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"
  hostname = "lab4"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "Cx4O9S5lwjQpAoHyhGnJf7oer12WClou_YLTE3zcBIoGamO29wZEgOoaVjf6RZtuhYfHldnr8g08rURD7TGu6A=="
  organization = "iks"
  bucket = "lab4_bucket"
  timeout = "15s"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "overlay"]

[[inputs.net]]

[[inputs.system]]
